baseURL: https://risotto.joeroe.io
theme: risotto
title: Lorenzo
author: Joe Roe
copyright: © 2021 Joe Roe
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
ignoreErrors: error-remote-getjson
sectionPagesMenu: main
params:
  about:
    description: Theme used:[hugo](https://gohugo.io) <br>
                 Do or do not. There is no try.
    logo: images/rice.svg
    title: risotto
  socialLinks:
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/Lorenzomicci
    - icon: fas fa-envelope
      title: Email
      url: mailto:lorenzo.micci@studenti.unicam.it
  theme:
    mode: dark-mode
    palette: gruvbox-dark
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
taxonomies:
  category: categories
  series: series
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: yes
privacy:
  instagram:
    disabled: no
    simple: yes
  twitter:
    disabled: no
    enableDNT: yes
    simple: yes
  vimeo:
    disabled: no
    simple: yes
  youtube:
    disabled: no
    privacyEnhanced: yes
services:
  instagram:
    disableInlineCSS: yes
  twitter:
    disableInlineCSS: yes
